# <b><i> Pandas Level 1<b><i>

In [11]:
import pandas as pd

Data_01 = [1,2,3,4,5]
seres = pd.Series(Data_01)
seres

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Pass either list of TUPPLE
# index=None, dtype=None, name=None

import pandas as pd
Data_01 = (1,2,3,4,5)
Series  = pd.Series(Data_01)
Series

In [ ]:
import pandas as pd
Data_01 = (1,2,3,4,5)
Series  = pd.Series(Data_01, colun)
Series

In [ ]:
# Using Dict, you will get index as well of your choice
Data_01 = {"KEY_1":1,"KEY_2":2,"KEY_3":3}
Data_01
pd.Series(Data_01)

In [6]:
# Create the Series uisng Dictinary Pandas
calories = {"day1": 420, "day2": 380, "day3": 390}
calSeries = pd.Series(calories,)
calSeries

day1    420
day2    380
day3    390
dtype: int64

# DataFrame

In [1]:
import pandas as pd
new_Dict = {'Name':["Rajesh","Sunil","Prakash"],
            "Age":[20,30,40]}

df = pd.DataFrame(new_Dict)
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [2]:
new_List = [["Rajesh",20],
            ["Sunil",30],
            ["Prakash",40]]

pd.DataFrame(new_List,columns=["Names","Age"])

     Names  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [3]:
# Create Dataframe from Dictionary
data = {"calories" : [420, 380, 390],
        "duration" : [50,  40,   45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [4]:
# Create Dataframe from Dictionary
data = {"Name" : ["Mohit", "Vishal", "Shubham"],
        "duration" : [21, 16, 24],
        "Qualification" :["BCA", "Physics", "11th"]}
df = pd.DataFrame(data)
df

      Name  duration Qualification
0    Mohit        21           BCA
1   Vishal        16       Physics
2  Shubham        24          11th

In [5]:
# Read file

file_Path = "M:/Download/Edge/Small Airline.csv"
df = pd.read_csv(file_Path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,23:30,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,21:35,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,12-03-2019,10:25,18:55,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

In [6]:
# Read file

file_Path = "M:/Download/Edge/Small Airline.csv"
df = pd.read_csv(file_Path)
df

df.to_excel("M:/Download/new.xlsx")

In [19]:
! pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First_name       17 non-null     object
 1   Last_name        17 non-null     object
 2   Age              15 non-null     float64
 3   City             15 non-null     object
 4   Airline          15 non-null     object
 5   Date_of_Journey  17 non-null     object
 6   Dep_Time         17 non-null     object
 7   Arrival_Time     17 non-null     object
 8   Dept_Hour        17 non-null     int64
 9   Dept_Minute      17 non-null     int64
 10  Arrival_Hour     17 non-null     int64
 11  Arrival_Minute   17 non-null     int64
 12  Full Name        17 non-null     object
dtypes: float64(1), int64(4), object(8)
memory usage: 1.9+ KB

In [27]:
df.describe()

ImportError: cannot import name 'format_name' from 'pandas.io.formats.format' (c:\Users\mohit\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\io\formats\format.py)

             Age  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute
count  15.000000  17.000000    17.000000     17.000000       17.000000
mean   42.933333  10.529412    29.411765     12.058824       18.529412
std     4.757951   5.724046    19.193289      6.859943       14.004989
min    36.000000   5.000000     5.000000      1.000000        0.000000
25%    40.000000   5.000000    20.000000      8.000000       10.000000
50%    42.000000   9.000000    25.000000     10.000000       15.000000
75%    46.000000  11.000000    50.000000     19.000000       25.000000
max    52.000000  22.000000    55.000000     23.000000       55.000000

In [23]:
df.columns

Index(['First_name', 'Last_name', 'Age', 'City', 'Airline', 'Date_of_Journey',
       'Dep_Time', 'Arrival_Time', 'Dept_Hour', 'Dept_Minute', 'Arrival_Hour',
       'Arrival_Minute', 'Full Name'],
      dtype='object')

In [26]:
df["Age"].unique()

array([42., 52., 36., nan, 39., 43., 45., 40., 47.])

In [15]:
df.describe()

             Age  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute
count  15.000000  17.000000    17.000000     17.000000       17.000000
mean   42.933333  10.529412    29.411765     12.058824       18.529412
std     4.757951   5.724046    19.193289      6.859943       14.004989
min    36.000000   5.000000     5.000000      1.000000        0.000000
25%    40.000000   5.000000    20.000000      8.000000       10.000000
50%    42.000000   9.000000    25.000000     10.000000       15.000000
75%    46.000000  11.000000    50.000000     19.000000       25.000000
max    52.000000  22.000000    55.000000     23.000000       55.000000

In [29]:
import sys
print(sys.executable)
%pip install --upgrade jinja2

c:\Users\mohit\AppData\Local\Programs\Python\Python314\python.exe
Requirement already satisfied: jinja2 in c:\Users\mohit\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\mohit\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [7]:
df.nunique()

First_name         12
Last_name          10
Age                 8
City                5
Airline             4
Date_of_Journey     7
Dep_Time            9
Arrival_Time        9
Dept_Hour           8
Dept_Minute         5
Arrival_Hour        9
Arrival_Minute      7
Full Name          12
dtype: int64

In [17]:
df['Age'].mode()

0    40.0
Name: Age, dtype: float64

In [19]:
df[['First_name', 'City']]

   First_name       City
0         Ram  BANGALURU
1       Mohan    CHENNAI
2        Tina       Pune
3       Jeetu      Delhi
4       Meera    LUCKNOW
5         Ram  BANGALURU
6       Mohan    CHENNAI
7      Rajesh        NaN
8      Sanjay        NaN
9     Trishul       Pune
10     Sameer      Delhi
11       Amol    LUCKNOW
12    Praveen  BANGALURU
13     Sunita    CHENNAI
14       Amol    LUCKNOW
15    Praveen  BANGALURU
16     Sunita    CHENNAI

In [20]:
df[13:14]

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

In [33]:
#row and column filtering using loc
df.loc[[4,5,6,7], ['First_name', 'Age']]
df.loc[4:5, ['First_name', 'Age']]
df.loc[4:8,['City', 'Airline']]

        City      Airline
4    LUCKNOW       IndiGo
5  BANGALURU          NaN
6    CHENNAI          NaN
7        NaN  Jet Airways
8        NaN  Jet Airways

In [32]:
df.iloc[3:5,[3,5]]
df.iloc[1:,[3,5]]

         City Date_of_Journey
1     CHENNAI      01-05-2019
2        Pune      09-06-2019
3       Delhi      12-05-2019
4     LUCKNOW      01-03-2019
5   BANGALURU      24-03-2019
6     CHENNAI      01-05-2019
7         NaN      01-03-2019
8         NaN      12-03-2019
9        Pune      27-05-2019
10      Delhi      12-03-2019
11    LUCKNOW      01-03-2019
12  BANGALURU      12-03-2019
13    CHENNAI      27-05-2019
14    LUCKNOW      01-03-2019
15  BANGALURU      12-03-2019
16    CHENNAI      27-05-2019